[package]
name = "map2prop-rs"
authors = [ "Lê Hàn Minh Khang (Khang Le) <mkhangle20@gmail.com>" ]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.27.0"
map = { path = "map" }
qc = { version = "0.1.0", path = "qc" }
rayon = "1.10.0"
rhai = "1.17.1"
smd = { path = "smd" }

# egui stuffs
eframe = "0.27.2"
env_logger = "0.11.3"
egui_tiles = "0.8.0"
rfd = "0.14.1"

[workspace]
members = [".", "map", "smd", "qc" ]
